# Generated by Django 5.2.5 on 2025-09-20 18:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('terminologies', '0020_ayurvedha_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminologyMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_system', models.CharField(help_text='e.g., NAMASTE-Ayurveda, NAMASTE-Siddha, NAMASTE-Unani', max_length=200)),
                ('target_system', models.CharField(default='ICD-11', help_text='Target terminology system', max_length=200)),
                ('biobert_model', models.CharField(default='nlpie/tiny-biobert', help_text='TinyBioBERT model identifier for ONNX', max_length=200)),
                ('similarity_threshold', models.FloatField(default=0.75, help_text='Minimum cosine similarity for creating mappings')),
                ('confidence_boost', models.FloatField(default=0.05, help_text='Confidence boost for high-quality mappings')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('review', 'Under Review'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('last_mapping_run', models.DateTimeField(blank=True, null=True)),
                ('total_mappings', models.PositiveIntegerField(default=0)),
                ('validated_mappings', models.PositiveIntegerField(default=0)),
                ('high_confidence_mappings', models.PositiveIntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('average_similarity', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Terminology Mapping',
                'verbose_name_plural': 'Terminology Mappings',
                'db_table': 'terminology_mappings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_system', 'target_system'], name='terminology_source__28b37d_idx'), models.Index(fields=['status', 'is_active'], name='terminology_status_e9609d_idx'), models.Index(fields=['created_at'], name='terminology_created_7292bb_idx'), models.Index(fields=['last_mapping_run'], name='terminology_last_ma_717172_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConceptMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_object_id', models.PositiveIntegerField()),
                ('relationship', models.CharField(choices=[('equivalent', 'Equivalent'), ('related-to', 'Related To'), ('source-is-narrower-than-target', 'Source Is Narrower'), ('source-is-broader-than-target', 'Source Is Broader'), ('not-related-to', 'Not Related')], default='related-to', max_length=35)),
                ('similarity_score', models.FloatField(help_text='Cosine similarity score from BioBERT embeddings (0.0 to 1.0)')),
                ('confidence_score', models.FloatField(help_text='Adjusted confidence score with domain-specific boosts')),
                ('source_embedding', models.JSONField(blank=True, help_text='768-dimensional source embedding from BioBERT', null=True)),
                ('target_embedding', models.JSONField(blank=True, help_text='768-dimensional target embedding from BioBERT', null=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Has this mapping been reviewed by a domain expert?')),
                ('validation_notes', models.TextField(blank=True, help_text='Expert notes on mapping quality or corrections needed')),
                ('validated_by', models.CharField(blank=True, help_text='Username of expert who validated this mapping', max_length=255)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('mapping_method', models.CharField(choices=[('onnx_biobert', 'ONNX TinyBioBERT Automatic'), ('manual', 'Manual Entry'), ('hybrid', 'AI + Manual Review'), ('imported', 'Imported from External Source')], default='onnx_biobert', max_length=20)),
                ('is_high_confidence', models.BooleanField(default=False, help_text='Automatically set for mappings with confidence >= 0.9')),
                ('needs_review', models.BooleanField(default=True, help_text='Flag for mappings that need expert review')),
                ('has_issues', models.BooleanField(default=False, help_text='Flag for problematic mappings')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('target_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_mappings', to='terminologies.icd11term')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_mappings', to='namasthe_mapping.terminologymapping')),
            ],
            options={
                'verbose_name': 'Concept Mapping',
                'verbose_name_plural': 'Concept Mappings',
                'db_table': 'concept_mappings',
                'ordering': ['-confidence_score', '-similarity_score'],
            },
        ),
        migrations.CreateModel(
            name='MappingAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('validate', 'Validated'), ('flag', 'Flagged for Review'), ('delete', 'Deleted')], max_length=20)),
                ('field_changes', models.JSONField(default=dict, help_text='JSON object showing old_value -> new_value for each changed field')),
                ('reason', models.TextField(blank=True, help_text='Reason for the change (user input or system note)')),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('system_version', models.CharField(blank=True, max_length=100)),
                ('biobert_model_version', models.CharField(blank=True, max_length=200)),
                ('concept_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='namasthe_mapping.conceptmapping')),
            ],
            options={
                'verbose_name': 'Mapping Audit Entry',
                'verbose_name_plural': 'Mapping Audit Entries',
                'db_table': 'mapping_audit',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['concept_mapping', 'timestamp'], name='mapping_aud_concept_443b5e_idx'), models.Index(fields=['action', 'timestamp'], name='mapping_aud_action_4dcac2_idx'), models.Index(fields=['user_name', 'timestamp'], name='mapping_aud_user_na_4b2ff9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conceptmapping',
            index=models.Index(fields=['mapping', 'is_validated'], name='concept_map_mapping_5a3d67_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptmapping',
            index=models.Index(fields=['mapping', 'relationship'], name='concept_map_mapping_f0996c_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptmapping',
            index=models.Index(fields=['similarity_score'], name='concept_map_similar_6dc088_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptmapping',
            index=models.Index(fields=['confidence_score'], name='concept_map_confide_2a6382_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptmapping',
            index=models.Index(fields=['is_high_confidence'], name='concept_map_is_high_333b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptmapping',
            index=models.Index(fields=['needs_review'], name='concept_map_needs_r_ea93a7_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptmapping',
            index=models.Index(fields=['mapping_method'], name='concept_map_mapping_934bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptmapping',
            index=models.Index(fields=['created_at'], name='concept_map_created_75f8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptmapping',
            index=models.Index(fields=['mapping', 'is_validated', 'confidence_score'], name='concept_map_mapping_82a926_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptmapping',
            index=models.Index(fields=['source_content_type', 'mapping'], name='concept_map_source__49efae_idx'),
        ),
        migrations.AddIndex(
            model_name='conceptmapping',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='concept_mapping_search_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='conceptmapping',
            unique_together={('mapping', 'source_content_type', 'source_object_id', 'target_concept')},
        ),
    ]
