# Generated by Django 5.2.5 on 2025-09-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namasthe_mapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptmapping',
            name='mapping_method',
            field=models.CharField(choices=[('onnx_biobert', 'ONNX TinyBioBERT Automatic'), ('manual', 'Manual Entry'), ('hybrid', 'AI + Manual Review'), ('imported', 'Imported from External Source')], default='onnx_biobert', max_length=50),
        ),
    ]
