# Generated by Django 5.2.5 on 2025-09-09 16:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminologies', '0005_add_pg_trgm_extension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayurvedhamodel',
            options={'verbose_name': 'Ayurveda Term', 'verbose_name_plural': 'Ayurveda Terms'},
        ),
        migrations.AlterModelOptions(
            name='icd11term',
            options={'verbose_name': 'ICD-11 Term', 'verbose_name_plural': 'ICD-11 Terms'},
        ),
        migrations.AlterModelOptions(
            name='icdclasskind',
            options={'verbose_name': 'ICD Class Kind', 'verbose_name_plural': 'ICD Class Kinds'},
        ),
        migrations.AlterModelOptions(
            name='siddhamodel',
            options={'verbose_name': 'Siddha Term', 'verbose_name_plural': 'Siddha Terms'},
        ),
        migrations.AlterModelOptions(
            name='unanimodel',
            options={'verbose_name': 'Unani Term', 'verbose_name_plural': 'Unani Terms'},
        ),
        migrations.AddField(
            model_name='ayurvedhamodel',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icd11term',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siddhamodel',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unanimodel',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ayurvedhamodel',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ayurvedhamodel',
            name='diacritical_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ayurvedhamodel',
            name='english_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ayurvedhamodel',
            name='hindi_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='icd11term',
            name='chapter_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='icd11term',
            name='class_kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='terminologies.icdclasskind'),
        ),
        migrations.AlterField(
            model_name='icd11term',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='icd11term',
            name='is_leaf',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='icd11term',
            name='is_residual',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='icd11term',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='icdclasskind',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='siddhamodel',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='siddhamodel',
            name='english_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siddhamodel',
            name='romanized_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siddhamodel',
            name='tamil_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unanimodel',
            name='arabic_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unanimodel',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='unanimodel',
            name='english_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unanimodel',
            name='romanized_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='ayurvedhamodel',
            index=models.Index(fields=['hindi_name'], name='ayurveda_te_hindi_n_461605_idx'),
        ),
        migrations.AddIndex(
            model_name='ayurvedhamodel',
            index=models.Index(fields=['diacritical_name'], name='ayurveda_te_diacrit_71782f_idx'),
        ),
        migrations.AddIndex(
            model_name='ayurvedhamodel',
            index=models.Index(fields=['english_name', 'hindi_name'], name='ayurveda_te_english_fc677f_idx'),
        ),
        migrations.AddIndex(
            model_name='ayurvedhamodel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ayurveda_search_gin'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=models.Index(fields=['code'], name='icd11_terms_code_87f4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=models.Index(fields=['title'], name='icd11_terms_title_d2b758_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=models.Index(fields=['chapter_no'], name='icd11_terms_chapter_61f17e_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=models.Index(fields=['code', 'title'], name='icd11_terms_code_b2c9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=models.Index(fields=['chapter_no', 'is_leaf'], name='icd11_terms_chapter_429727_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=models.Index(fields=['is_residual', 'chapter_no'], name='icd11_terms_is_resi_aeec85_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='icd11_search_gin'),
        ),
        migrations.AddIndex(
            model_name='siddhamodel',
            index=models.Index(fields=['tamil_name'], name='siddha_term_tamil_n_caf262_idx'),
        ),
        migrations.AddIndex(
            model_name='siddhamodel',
            index=models.Index(fields=['romanized_name'], name='siddha_term_romaniz_1dd28c_idx'),
        ),
        migrations.AddIndex(
            model_name='siddhamodel',
            index=models.Index(fields=['english_name', 'tamil_name'], name='siddha_term_english_d307c1_idx'),
        ),
        migrations.AddIndex(
            model_name='siddhamodel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='siddha_search_gin'),
        ),
        migrations.AddIndex(
            model_name='unanimodel',
            index=models.Index(fields=['arabic_name'], name='unani_terms_arabic__c581a4_idx'),
        ),
        migrations.AddIndex(
            model_name='unanimodel',
            index=models.Index(fields=['romanized_name'], name='unani_terms_romaniz_41616a_idx'),
        ),
        migrations.AddIndex(
            model_name='unanimodel',
            index=models.Index(fields=['english_name', 'arabic_name'], name='unani_terms_english_37c26e_idx'),
        ),
        migrations.AddIndex(
            model_name='unanimodel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='unani_search_gin'),
        ),
        migrations.AddConstraint(
            model_name='icd11term',
            constraint=models.CheckConstraint(condition=models.Q(('depth_in_kind__gte', 0)), name='positive_depth_in_kind'),
        ),
        migrations.AddConstraint(
            model_name='icd11term',
            constraint=models.CheckConstraint(condition=models.Q(('no_of_non_residual_children__gte', 0)), name='positive_children_count'),
        ),
        migrations.AlterModelTable(
            name='ayurvedhamodel',
            table='ayurveda_terms',
        ),
        migrations.AlterModelTable(
            name='icd11term',
            table='icd11_terms',
        ),
        migrations.AlterModelTable(
            name='icdclasskind',
            table='icd_class_kinds',
        ),
        migrations.AlterModelTable(
            name='siddhamodel',
            table='siddha_terms',
        ),
        migrations.AlterModelTable(
            name='unanimodel',
            table='unani_terms',
        ),
    ]
