# Generated by Django 5.2.5 on 2025-09-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminologies', '0008_add_search_vector_triggers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AyurvedhaModel',
            new_name='Ayurvedha',
        ),
        migrations.RenameModel(
            old_name='SiddhaModel',
            new_name='Siddha',
        ),
        migrations.RenameModel(
            old_name='UnaniModel',
            new_name='Unani',
        ),
    ]
