# Generated by Django 5.2.5 on 2025-09-11 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminologies', '0009_rename_ayurvedhamodel_ayurvedha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd_similarity', models.FloatField()),
                ('cross_ayurveda_similarity', models.FloatField(blank=True, null=True)),
                ('cross_siddha_similarity', models.FloatField(blank=True, null=True)),
                ('cross_unani_similarity', models.FloatField(blank=True, null=True)),
                ('source_system', models.CharField(choices=[('ayurveda', 'Ayurveda'), ('siddha', 'Siddha'), ('unani', 'Unani')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('cross_ayurveda_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_mappings', to='terminologies.ayurvedha')),
                ('cross_siddha_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_mappings', to='terminologies.siddha')),
                ('cross_unani_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_mappings', to='terminologies.unani')),
                ('icd_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namaste_mappings', to='terminologies.icd11term')),
                ('primary_ayurveda_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terminologies.ayurvedha')),
                ('primary_siddha_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terminologies.siddha')),
                ('primary_unani_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terminologies.unani')),
            ],
            options={
                'db_table': 'namaste_to_icd_mappings',
                'indexes': [models.Index(fields=['source_system'], name='namaste_to__source__4e048d_idx'), models.Index(fields=['confidence_score'], name='namaste_to__confide_b63069_idx'), models.Index(fields=['primary_ayurveda_term'], name='namaste_to__primary_64b4dd_idx'), models.Index(fields=['primary_siddha_term'], name='namaste_to__primary_9e4cb7_idx'), models.Index(fields=['primary_unani_term'], name='namaste_to__primary_0a1349_idx')],
                'unique_together': {('primary_ayurveda_term', 'icd_term'), ('primary_siddha_term', 'icd_term'), ('primary_unani_term', 'icd_term')},
            },
        ),
    ]
