# Generated by Django 5.2.5 on 2025-09-16 20:16

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terminologies", "0010_termmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="ICD11Synonym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "verbose_name": "ICD-11 Synonym",
                "verbose_name_plural": "ICD-11 Synonyms",
                "db_table": "icd11_synonyms",
            },
        ),
        migrations.RemoveField(
            model_name="icd11term",
            name="class_kind",
        ),
        migrations.RemoveConstraint(
            model_name="icd11term",
            name="positive_depth_in_kind",
        ),
        migrations.RemoveConstraint(
            model_name="icd11term",
            name="positive_children_count",
        ),
        migrations.RemoveIndex(
            model_name="icd11term",
            name="icd11_terms_chapter_61f17e_idx",
        ),
        migrations.RemoveIndex(
            model_name="icd11term",
            name="icd11_terms_code_b2c9ff_idx",
        ),
        migrations.RemoveIndex(
            model_name="icd11term",
            name="icd11_terms_chapter_429727_idx",
        ),
        migrations.RemoveIndex(
            model_name="icd11term",
            name="icd11_terms_is_resi_aeec85_idx",
        ),
        migrations.RemoveField(
            model_name="icd11term",
            name="browser_link",
        ),
        migrations.RemoveField(
            model_name="icd11term",
            name="chapter_no",
        ),
        migrations.RemoveField(
            model_name="icd11term",
            name="depth_in_kind",
        ),
        migrations.RemoveField(
            model_name="icd11term",
            name="icat_link",
        ),
        migrations.RemoveField(
            model_name="icd11term",
            name="is_leaf",
        ),
        migrations.RemoveField(
            model_name="icd11term",
            name="is_residual",
        ),
        migrations.RemoveField(
            model_name="icd11term",
            name="linearization_uri",
        ),
        migrations.RemoveField(
            model_name="icd11term",
            name="no_of_non_residual_children",
        ),
        migrations.RemoveField(
            model_name="icd11term",
            name="primary_location",
        ),
        migrations.RemoveField(
            model_name="icd11term",
            name="version_date",
        ),
        migrations.AddField(
            model_name="icd11synonym",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="synonyms",
                to="terminologies.icd11term",
            ),
        ),
        migrations.DeleteModel(
            name="ICDClassKind",
        ),
        migrations.AddIndex(
            model_name="icd11synonym",
            index=models.Index(fields=["label"], name="icd11_synon_label_b326a3_idx"),
        ),
        migrations.AddField(
            model_name="icd11synonym",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="icd11synonym",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="icd11_synonym_search_gin"
            ),
        ),
    ]
