# Generated by Django 5.2.5 on 2025-09-16 20:25
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False  # Required for CONCURRENTLY operations

    dependencies = [
        ("terminologies", "0011_icd11synonym_remove_icd11term_class_kind_and_more"),
    ]

    operations = [
        # ICD11Term trigram indexes
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS icd11_code_trgm_idx "
            "ON icd11_terms USING GIN(code gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS icd11_code_trgm_idx;",
        ),
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS icd11_title_trgm_idx "
            "ON icd11_terms USING GIN(title gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS icd11_title_trgm_idx;",
        ),
        # ICD11Synonym trigram index
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS icd11_synonym_label_trgm_idx "
            "ON icd11_synonyms USING GIN(label gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS icd11_synonym_label_trgm_idx;",
        ),
    ]
