# Generated by Django 5.2.5 on 2025-09-16 21:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("terminologies", "0013_new_triggers_ICD11"),
    ]

    operations = [
        migrations.AddField(
            model_name="icd11synonym",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="icd11synonym",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="icd11_synonym_search_gin"
            ),
        ),
    ]
