# Generated by Django 5.2.5 on 2025-09-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminologies', '0013_new_triggers_ICD11'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ICD11Synonym',
        ),
    ]
