# Generated by Django 5.2.5 on 2025-09-18 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminologies', '0014_delete_icd11synonym'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icd11term',
            options={'verbose_name': 'ICD Term', 'verbose_name_plural': 'ICD Terms'},
        ),
        migrations.RenameIndex(
            model_name='icd11term',
            new_name='icd_terms_code_b76c2b_idx',
            old_name='icd11_terms_code_87f4b2_idx',
        ),
        migrations.RenameIndex(
            model_name='icd11term',
            new_name='icd_terms_title_6701af_idx',
            old_name='icd11_terms_title_d2b758_idx',
        ),
        migrations.RenameIndex(
            model_name='icd11term',
            new_name='icd_search_gin',
            old_name='icd11_search_gin',
        ),
        migrations.AddField(
            model_name='icd11term',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icd11term',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icd11term',
            name='long_definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icd11term',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=models.Index(fields=['created_at'], name='icd_terms_created_bb872c_idx'),
        ),
        migrations.AlterModelTable(
            name='icd11term',
            table='icd_terms',
        ),
    ]
