# Generated by Django 5.2.5 on 2025-09-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminologies', '0015_alter_icd11term_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icd11term',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='icd11term',
            name='icd_terms_code_b76c2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='icd11term',
            name='icd_terms_title_6701af_idx',
        ),
        migrations.RemoveIndex(
            model_name='icd11term',
            name='icd_search_gin',
        ),
        migrations.RemoveIndex(
            model_name='icd11term',
            name='icd_terms_created_bb872c_idx',
        ),
        migrations.AddField(
            model_name='icd11term',
            name='browser_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='icd11term',
            name='class_kind',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='icd11term',
            name='exclusions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='icd11term',
            name='inclusions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='icd11term',
            name='index_terms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='icd11term',
            name='parent',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='icd11term',
            name='postcoordination_scales',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='icd11term',
            name='related_perinatal_entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='icd11term',
            name='source',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='icd11term',
            name='foundation_uri',
            field=models.URLField(db_index=True, max_length=500, unique=True),
        ),
        migrations.AlterModelTable(
            name='icd11term',
            table=None,
        ),
    ]
