# Generated by Django 5.2.5 on 2025-09-18 17:33

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminologies', '0016_alter_icd11term_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icd11term',
            options={'verbose_name': 'ICD-11 Term', 'verbose_name_plural': 'ICD-11 Terms'},
        ),
        migrations.AddIndex(
            model_name='ayurvedha',
            index=django.contrib.postgres.indexes.GinIndex(fields=['english_name'], name='ayurveda_english_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='ayurvedha',
            index=django.contrib.postgres.indexes.GinIndex(fields=['hindi_name'], name='ayurveda_hindi_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='ayurvedha',
            index=django.contrib.postgres.indexes.GinIndex(fields=['diacritical_name'], name='ayurveda_diacritical_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='ayurvedha',
            index=django.contrib.postgres.indexes.GinIndex(fields=['code'], name='ayurveda_code_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=models.Index(fields=['code'], name='icd11_terms_code_87f4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=models.Index(fields=['title'], name='icd11_terms_title_d2b758_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=models.Index(fields=['foundation_uri'], name='icd11_terms_foundat_0d520d_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=models.Index(fields=['class_kind'], name='icd11_terms_class_k_7e3803_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=models.Index(fields=['created_at'], name='icd11_terms_created_46f31f_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=models.Index(fields=['code', 'title'], name='icd11_terms_code_b2c9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=models.Index(fields=['class_kind', 'created_at'], name='icd11_terms_class_k_777e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='icd11_search_gin'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=django.contrib.postgres.indexes.GinIndex(fields=['index_terms'], name='icd11_index_terms_gin'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=django.contrib.postgres.indexes.GinIndex(fields=['inclusions'], name='icd11_inclusions_gin'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=django.contrib.postgres.indexes.GinIndex(fields=['exclusions'], name='icd11_exclusions_gin'),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='icd11_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=django.contrib.postgres.indexes.GinIndex(fields=['code'], name='icd11_code_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='siddha',
            index=django.contrib.postgres.indexes.GinIndex(fields=['english_name'], name='siddha_english_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='siddha',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tamil_name'], name='siddha_tamil_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='siddha',
            index=django.contrib.postgres.indexes.GinIndex(fields=['romanized_name'], name='siddha_romanized_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='siddha',
            index=django.contrib.postgres.indexes.GinIndex(fields=['code'], name='siddha_code_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='unani',
            index=django.contrib.postgres.indexes.GinIndex(fields=['english_name'], name='unani_english_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='unani',
            index=django.contrib.postgres.indexes.GinIndex(fields=['arabic_name'], name='unani_arabic_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='unani',
            index=django.contrib.postgres.indexes.GinIndex(fields=['romanized_name'], name='unani_romanized_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='unani',
            index=django.contrib.postgres.indexes.GinIndex(fields=['code'], name='unani_code_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterModelTable(
            name='icd11term',
            table='icd11_terms',
        ),
    ]
