# Generated by Django 5.2.5 on 2025-09-18 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("terminologies", "0017_alter_icd11term_options_and_more"),
    ]

    operations = [
        # Ensure pg_trgm extension is enabled
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;",
        ),
        # ICD11Term trigram indexes
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS icd11_title_trgm_gin ON icd11_terms USING gin (title gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS icd11_title_trgm_gin;",
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS icd11_code_trgm_gin ON icd11_terms USING gin (code gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS icd11_code_trgm_gin;",
        ),
        # Ayurveda trigram indexes
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS ayurveda_english_trgm_gin ON ayurveda_terms USING gin (english_name gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS ayurveda_english_trgm_gin;",
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS ayurveda_hindi_trgm_gin ON ayurveda_terms USING gin (hindi_name gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS ayurveda_hindi_trgm_gin;",
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS ayurveda_diacritical_trgm_gin ON ayurveda_terms USING gin (diacritical_name gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS ayurveda_diacritical_trgm_gin;",
        ),
        # Siddha trigram indexes
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS siddha_english_trgm_gin ON siddha_terms USING gin (english_name gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS siddha_english_trgm_gin;",
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS siddha_tamil_trgm_gin ON siddha_terms USING gin (tamil_name gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS siddha_tamil_trgm_gin;",
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS siddha_romanized_trgm_gin ON siddha_terms USING gin (romanized_name gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS siddha_romanized_trgm_gin;",
        ),
        # Unani trigram indexes
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS unani_english_trgm_gin ON unani_terms USING gin (english_name gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS unani_english_trgm_gin;",
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS unani_arabic_trgm_gin ON unani_terms USING gin (arabic_name gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS unani_arabic_trgm_gin;",
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS unani_romanized_trgm_gin ON unani_terms USING gin (romanized_name gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS unani_romanized_trgm_gin;",
        ),
    ]
