# Generated by Django 5.2.5 on 2025-09-18 17:42
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("terminologies", "0018_add_fuzzy_search_indexes"),
    ]

    operations = [
        # ICD11Term trigger - DROP FIRST, then CREATE
        migrations.RunSQL(
            sql="""
            DROP TRIGGER IF EXISTS icd11_search_vector_trigger ON icd11_terms;
            DROP FUNCTION IF EXISTS update_icd11_search_vector();
            
            CREATE OR REPLACE FUNCTION update_icd11_search_vector()
            RETURNS trigger AS $$
            BEGIN
                NEW.search_vector := 
                    setweight(to_tsvector('english', COALESCE(NEW.title, '')), 'A') ||
                    setweight(to_tsvector('english', COALESCE(NEW.code, '')), 'A') ||
                    setweight(to_tsvector('english', COALESCE(NEW.definition, '')), 'B') ||
                    setweight(to_tsvector('english', COALESCE(NEW.long_definition, '')), 'C');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            CREATE TRIGGER icd11_search_vector_trigger
                BEFORE INSERT OR UPDATE ON icd11_terms
                FOR EACH ROW EXECUTE FUNCTION update_icd11_search_vector();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS icd11_search_vector_trigger ON icd11_terms;
            DROP FUNCTION IF EXISTS update_icd11_search_vector();
            """,
        ),
        # Ayurveda trigger - DROP FIRST, then CREATE
        migrations.RunSQL(
            sql="""
            DROP TRIGGER IF EXISTS ayurveda_search_vector_trigger ON ayurveda_terms;
            DROP FUNCTION IF EXISTS update_ayurveda_search_vector();
            
            CREATE OR REPLACE FUNCTION update_ayurveda_search_vector()
            RETURNS trigger AS $$
            BEGIN
                NEW.search_vector := 
                    setweight(to_tsvector('english', COALESCE(NEW.code, '')), 'A') ||
                    setweight(to_tsvector('english', COALESCE(NEW.english_name, '')), 'A') ||
                    setweight(to_tsvector('simple', COALESCE(NEW.hindi_name, '')), 'B') ||
                    setweight(to_tsvector('simple', COALESCE(NEW.diacritical_name, '')), 'B') ||
                    setweight(to_tsvector('english', COALESCE(NEW.description, '')), 'C');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            CREATE TRIGGER ayurveda_search_vector_trigger
                BEFORE INSERT OR UPDATE ON ayurveda_terms
                FOR EACH ROW EXECUTE FUNCTION update_ayurveda_search_vector();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS ayurveda_search_vector_trigger ON ayurveda_terms;
            DROP FUNCTION IF EXISTS update_ayurveda_search_vector();
            """,
        ),
        # Siddha trigger - DROP FIRST, then CREATE
        migrations.RunSQL(
            sql="""
            DROP TRIGGER IF EXISTS siddha_search_vector_trigger ON siddha_terms;
            DROP FUNCTION IF EXISTS update_siddha_search_vector();
            
            CREATE OR REPLACE FUNCTION update_siddha_search_vector()
            RETURNS trigger AS $$
            BEGIN
                NEW.search_vector := 
                    setweight(to_tsvector('english', COALESCE(NEW.code, '')), 'A') ||
                    setweight(to_tsvector('english', COALESCE(NEW.english_name, '')), 'A') ||
                    setweight(to_tsvector('simple', COALESCE(NEW.tamil_name, '')), 'B') ||
                    setweight(to_tsvector('english', COALESCE(NEW.romanized_name, '')), 'B') ||
                    setweight(to_tsvector('english', COALESCE(NEW.description, '')), 'C') ||
                    setweight(to_tsvector('english', COALESCE(NEW.reference, '')), 'D');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            CREATE TRIGGER siddha_search_vector_trigger
                BEFORE INSERT OR UPDATE ON siddha_terms
                FOR EACH ROW EXECUTE FUNCTION update_siddha_search_vector();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS siddha_search_vector_trigger ON siddha_terms;
            DROP FUNCTION IF EXISTS update_siddha_search_vector();
            """,
        ),
        # Unani trigger - DROP FIRST, then CREATE
        migrations.RunSQL(
            sql="""
            DROP TRIGGER IF EXISTS unani_search_vector_trigger ON unani_terms;
            DROP FUNCTION IF EXISTS update_unani_search_vector();
            
            CREATE OR REPLACE FUNCTION update_unani_search_vector()
            RETURNS trigger AS $$
            BEGIN
                NEW.search_vector := 
                    setweight(to_tsvector('english', COALESCE(NEW.code, '')), 'A') ||
                    setweight(to_tsvector('english', COALESCE(NEW.english_name, '')), 'A') ||
                    setweight(to_tsvector('simple', COALESCE(NEW.arabic_name, '')), 'B') ||
                    setweight(to_tsvector('english', COALESCE(NEW.romanized_name, '')), 'B') ||
                    setweight(to_tsvector('english', COALESCE(NEW.description, '')), 'C') ||
                    setweight(to_tsvector('english', COALESCE(NEW.reference, '')), 'D');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            CREATE TRIGGER unani_search_vector_trigger
                BEFORE INSERT OR UPDATE ON unani_terms
                FOR EACH ROW EXECUTE FUNCTION update_unani_search_vector();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS unani_search_vector_trigger ON unani_terms;
            DROP FUNCTION IF EXISTS update_unani_search_vector();
            """,
        ),
    ]
