# Generated by Django 5.2.5 on 2025-09-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminologies', '0019_add_search_vector_triggers2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayurvedha',
            name='embedding',
            field=models.JSONField(blank=True, help_text='768-dimensional TinyBioBERT embedding vector', null=True),
        ),
        migrations.AddField(
            model_name='ayurvedha',
            name='embedding_model_version',
            field=models.CharField(blank=True, help_text='BioBERT model version used for embedding', max_length=200),
        ),
        migrations.AddField(
            model_name='ayurvedha',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icd11term',
            name='embedding',
            field=models.JSONField(blank=True, help_text='768-dimensional TinyBioBERT embedding vector', null=True),
        ),
        migrations.AddField(
            model_name='icd11term',
            name='embedding_model_version',
            field=models.CharField(blank=True, help_text='BioBERT model version used for embedding', max_length=200),
        ),
        migrations.AddField(
            model_name='icd11term',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siddha',
            name='embedding',
            field=models.JSONField(blank=True, help_text='768-dimensional TinyBioBERT embedding vector', null=True),
        ),
        migrations.AddField(
            model_name='siddha',
            name='embedding_model_version',
            field=models.CharField(blank=True, help_text='BioBERT model version used for embedding', max_length=200),
        ),
        migrations.AddField(
            model_name='siddha',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unani',
            name='embedding',
            field=models.JSONField(blank=True, help_text='768-dimensional TinyBioBERT embedding vector', null=True),
        ),
        migrations.AddField(
            model_name='unani',
            name='embedding_model_version',
            field=models.CharField(blank=True, help_text='BioBERT model version used for embedding', max_length=200),
        ),
        migrations.AddField(
            model_name='unani',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='icd11term',
            index=models.Index(fields=['embedding_updated_at'], name='icd11_terms_embeddi_a021ac_idx'),
        ),
    ]
